# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Infobesity
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A Data Science portfolio documenting my learning path and various projects.
baseurl: ""
url: "https://underwhelmed-ape.github.io"
github_username:  underwhelmed-ape
twitter_username: UnderwhelmedApe
linkedin_username: in/james-ulyett-049a1238

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - paginate:3
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
paginate_path: "page:num"
collections:
  making:
    output: true
    permalink: /making/:path/
